import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './components/Navbar'
import { Toaster } from 'react-hot-toast'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className} >
                <div className='container bg-quinary md:mx-auto'>
                    <div><Toaster /></div>
                    <NavBar />
                    <div id="main" className='min-h-fit px-10 py-5'>
                        {children}
                    </div>
                    <Footer />
                </div>
            </body>
        </html>
    )
}
