import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from '@/components/Navbar'
import { Toaster } from 'react-hot-toast'
import Footer from '@/components/Footer'
import { CartProvider } from '../context/cart'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <CartProvider>
            <html lang="en">
                <body className={inter.className} >
                    <div className='container md:mx-auto px-40'>
                        <div><Toaster /></div>
                        <NavBar />
                        <div id="main" className='min-h-fit px-10 py-5 bg-quinary'>
                            {children}
                        </div>
                        <Footer />
                    </div>
                </body>
            </html>
        </CartProvider>
    )
}
